### PR TITLE
Update apple1.ts

### PR DESCRIPTION
**Pull request by gabrielsroka**

### CODE REVIEW

**Review by whscullin — APPROVED** [review]
Thank you for figuring that out and pointing out that I should document it 😄

**Comment by gabrielsroka** [comment]
ty.

pressing reset (shift+f1) also clears the screen. is it possible to separate those into 2 different buttons/functions? i think that's how the apple 1 worked.

**Comment by whscullin** [comment]
(I thought I'd merged this already, sorry). Yes, it's been on my todo list to fix both the reset behavior and the screen clear behavior - screen clearing is done by repeatedly sending blank characters while the clear screen button is down, not wiping everything at once, so in theory how long you hold down the clear screen button affects how much of the screen is cleared.

**Comment by gabrielsroka** [comment]
pressing ESC or printing it shows a `;`

```
0:a9 1b 20 ef ff 4c 0 ff r
```

image

whereas https://github.com/stid/Apple1JS doesn't

image

see also https://github.com/whscullin/apple1js/issues/40

**Pull request merged**
